from pathlib import Path
import shutil
from datetime import datetime, timezone

ROOT = Path(__file__).resolve().parents[2]
BASE = ROOT / 'docs/prototypes/pdf-reference-homepage-replica-v1.0.0'
TARGET = BASE / 'index-v1.0.10-production-readiness-preview-full-original-assets-v1.0.0.html'
DIAGNOSTIC = BASE / 'index-v1.0.10-production-readiness-preview-generated-diagnostic-preserved-v1.0.0.html'
LOGO = BASE / 'assets/approved/approved-header-logo-transparent-display-embedded-v1.0.0.base64.txt'
RECORD = ROOT / 'docs/dfw-homepage-v1.0.10-exact-visual-copy-clean-template-rebuild-execution-record-v1.0.0.md'
URL = 'https://aw3consulting.github.io/dfwmatchdayconcierge/docs/prototypes/pdf-reference-homepage-replica-v1.0.0/index-v1.0.10-production-readiness-preview-full-original-assets-v1.0.0.html'

if not DIAGNOSTIC.exists():
    shutil.copy2(TARGET, DIAGNOSTIC)

logo_b64 = ''.join(LOGO.read_text(encoding='utf-8').split())
logo_src = 'data:image/png;base64,' + logo_b64
now = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%SZ')

pending = 'Pending Approved Asset'
html = f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>DFW Matchday Concierge - v1.0.10 Clean Template Rebuild</title>
<meta name="description" content="Exact visual-copy clean template rebuild with approved header logo embedded and remaining visual assets pending approval." />
<meta name="robots" content="noindex,nofollow" />
<style>
:root{{--bg:#020b13;--shell:#031523;--panel:#06243b;--panel2:#031827;--gold:#d8a64b;--gold2:#f0c86b;--text:#f4f7f2;--muted:#b6c4ca;--line:rgba(216,166,75,.58);--blue:rgba(122,177,205,.28);--max:1024px;--font:"Arial Narrow",Arial,Helvetica,sans-serif;--r:6px}}*{{box-sizing:border-box}}html{{background:#000;scroll-behavior:smooth}}body{{margin:0;background:#000;color:var(--text);font-family:var(--font);line-height:1.15}}a{{color:inherit;text-decoration:none}}.skip-link{{position:absolute;left:-9999px}}.skip-link:focus{{left:10px;top:10px;z-index:9999;background:#fff;color:#000;padding:10px}}.approval-banner{{position:sticky;top:0;z-index:60;background:#4b1208;color:#fff;text-align:center;padding:8px 12px;font:700 11px Arial,sans-serif;letter-spacing:.04em;text-transform:uppercase}}.page-shell{{width:min(var(--max),100%);margin:auto;padding:0 18px 16px;overflow:hidden;background:linear-gradient(#031827,#02111d);border-inline:1px solid rgba(216,166,75,.18)}}.panel{{overflow:hidden;border:1px solid var(--line);border-radius:var(--r);background:linear-gradient(180deg,var(--panel),var(--panel2));box-shadow:inset 0 0 0 1px rgba(255,255,255,.03)}}h1,h2,h3,p{{margin-top:0}}h2{{margin-bottom:7px;color:var(--gold2);font-size:14px;letter-spacing:.04em;text-transform:uppercase}}h3{{margin-bottom:4px}}.button{{display:inline-flex;align-items:center;justify-content:center;gap:7px;min-height:30px;padding:0 14px;border-radius:3px;text-align:center;text-transform:uppercase;font-size:8.5px;font-weight:900;letter-spacing:.035em;line-height:1}}.button-gold{{border:1px solid #e7bd62;background:linear-gradient(#efc96f,#c99437);color:#061522}}.button-dark,.button-outline{{border:1px solid var(--line);background:rgba(0,0,0,.26);color:#fff}}.button-full{{width:100%;margin-top:7px}}.text-link{{color:var(--gold2);font-weight:900;text-transform:uppercase}}
.site-header{{position:sticky;top:29px;z-index:40;min-height:58px;display:grid;grid-template-columns:88px 170px minmax(0,1fr) 156px;align-items:center;gap:10px;background:linear-gradient(180deg,rgba(2,13,23,.98),rgba(2,13,23,.92));border-bottom:1px solid rgba(216,166,75,.22)}}.logo-cell,.brand-cell{{display:flex;align-items:center;justify-content:center;min-height:58px}}.site-logo{{display:block;width:76px;height:54px;object-fit:contain;background:transparent}}.brand-name{{font-size:13px;line-height:1.02;font-weight:900;letter-spacing:.08em;text-transform:uppercase;text-align:center}}.brand-dfw{{color:var(--gold2)}}.primary-nav{{min-width:0;display:flex;align-items:center;justify-content:space-between;gap:10px;white-space:nowrap;text-transform:uppercase;font-size:7.2px;font-weight:900;letter-spacing:.01em;text-align:center}}.primary-nav a{{display:inline-flex;align-items:center;justify-content:center;flex:1 1 0;min-width:0}}.header-cta{{justify-self:stretch;min-height:32px;white-space:normal}}
.hero-section{{position:relative;min-height:252px;margin:0 -18px;overflow:hidden;display:grid;place-items:end center;border-bottom:1px solid rgba(216,166,75,.32);background:linear-gradient(180deg,rgba(4,20,35,.12),rgba(2,8,14,.86)),linear-gradient(90deg,#061a2c,#08243b 52%,#051522)}}.hero-section:before{{content:"HERO VISUAL ASSET PENDING APPROVAL";position:absolute;right:16px;top:14px;border:1px dashed rgba(240,200,107,.65);background:rgba(3,24,39,.78);color:var(--gold2);padding:7px 9px;font:900 8px Arial,sans-serif;letter-spacing:.06em;text-transform:uppercase}}.hero-content{{position:relative;max-width:760px;padding:70px 18px 18px;text-align:center;text-shadow:0 5px 16px #000}}.eyebrow{{margin-bottom:6px;color:var(--gold2);font-size:25px;text-transform:uppercase;font-weight:900;letter-spacing:.05em}}.hero-section h1{{margin:0 0 8px;font-size:44px;line-height:.92;letter-spacing:.045em;text-transform:uppercase}}.hero-subtitle{{max-width:620px;margin:0 auto 10px;color:#e1e8eb;font-size:11.5px;letter-spacing:.055em;font-weight:900;text-transform:uppercase}}.hero-actions{{display:flex;justify-content:center;gap:12px;flex-wrap:wrap}}.hero-note{{margin:8px 0 0;color:#d4dad9;font-size:8.8px;font-weight:800}}
.pending-panel,.image-slot,.icon-placeholder,.map-visual,.card-image-slot,.footer-logo-placeholder,.social-icon{{display:grid;place-items:center;position:relative;overflow:hidden;border:1px dashed rgba(240,200,107,.65);background:linear-gradient(135deg,rgba(216,166,75,.12),rgba(8,31,52,.88));color:var(--gold2);text-align:center;text-transform:uppercase;font-weight:900;letter-spacing:.06em}}.pending-panel:after,.image-slot:after,.map-visual:after,.card-image-slot:after,.footer-logo-placeholder:after{{content:"PENDING APPROVED ASSET";display:grid;place-items:center;position:absolute;inset:0;padding:8px;background:rgba(3,24,39,.76);font:900 9px/1.15 Arial,sans-serif;color:var(--gold2)}}.icon-placeholder:after,.social-icon:after{{content:"PENDING";display:grid;place-items:center;position:absolute;inset:0;background:rgba(3,24,39,.78);font:900 5.5px/1 Arial,sans-serif;color:var(--gold2)}}
.inquiry-panel{{display:grid;grid-template-columns:142px 1fr;gap:12px;padding:10px;margin:9px 0 7px}}.ai-image-slot{{min-height:112px}}.split-heading{{display:flex;justify-content:space-between;gap:10px;align-items:start}}.panel-heading p{{margin:1px 0 6px;color:#c7d5dc;font-size:9px}}.status-badge{{width:112px;text-align:center;text-transform:uppercase;font-size:8px;font-weight:900;color:var(--gold2)}}.inquiry-form{{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:7px;align-items:end}}.field{{display:grid;gap:3px;min-width:0}}.field label{{font-size:8px;text-transform:uppercase;font-weight:900}}.field input,.field select{{width:100%;height:34px;padding:0 8px;border:1px solid var(--blue);border-radius:4px;background:#082138;color:#cbd7dc;font-size:9px}}.field-wide,.field-notes{{grid-column:span 2}}.form-submit{{border:0;cursor:pointer;height:34px;align-self:end}}.matchday-calendar{{grid-column:1 / span 4;display:flex;align-items:center;gap:4px;min-height:24px;overflow:hidden}}.matchday-calendar b{{margin-right:3px;color:var(--gold2);font-size:7px;text-transform:uppercase;white-space:nowrap}}.matchday-calendar span{{display:inline-grid;place-items:center;min-width:40px;height:18px;border:1px solid var(--gold);background:rgba(216,166,75,.14);color:#f7d889;font-size:7px;font-weight:900;text-transform:uppercase}}.secure-note{{grid-column:5;grid-row:3;margin:-3px 0 0;text-align:center;font-size:7.5px;color:#b8c4ca}}
.paths-panel{{padding:10px}}.path-grid{{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:8px}}.path-card{{min-height:86px;padding:8px 6px;text-align:center;border:1px solid rgba(216,166,75,.5);border-radius:5px;background:#08243a}}.icon-placeholder{{height:27px;width:32px;margin:0 auto 4px}}.path-card h3{{margin:0 0 5px;font-size:10px;line-height:1.02;text-transform:uppercase}}.path-card p{{margin:0;color:#c5d1d7;font-size:7.8px}}.command-grid{{display:grid;gap:8px;margin-top:8px}}.command-grid-primary{{grid-template-columns:1.14fr .86fr}}.command-grid-lower{{grid-template-columns:repeat(3,1fr);align-items:stretch}}.map-panel,.team-mini-panel,.photo-card{{min-height:170px;padding:10px}}.photo-card{{display:flex;flex-direction:column}}.map-layout{{display:grid;grid-template-columns:1.05fr .95fr;gap:9px}}.map-visual{{min-height:154px;border-radius:5px}}.route-list{{display:grid;gap:5px;align-content:start}}.route-list a:not(.button){{padding:7px 8px;border:1px solid var(--blue);border-radius:4px;background:rgba(255,255,255,.04);font-size:8.5px}}.opening-team-grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;flex:1}}.opening-team-grid article{{display:flex;flex-direction:column;justify-content:space-between;min-height:63px;border:1px solid var(--blue);background:#092339;text-align:center;text-transform:uppercase;font-size:7px;font-weight:900;overflow:hidden}}.opening-team-grid b{{display:block;padding:3px 1px}}.flag{{display:block;flex:1;min-height:42px}}.flag-ned{{background:linear-gradient(#be1e2d 0 33%,#fff 33% 66%,#244aa5 66%)}}.flag-jpn{{background:radial-gradient(circle,#c91f2d 0 25%,transparent 26%),#fff}}.flag-eng{{background:linear-gradient(90deg,transparent 42%,#c91f2d 42% 58%,transparent 58%),linear-gradient(transparent 38%,#c91f2d 38% 62%,transparent 62%),#fff}}.flag-cro{{background:linear-gradient(#d91b2b 0 33%,#fff 33% 66%,#183a8f 66%)}}.flag-arg{{background:linear-gradient(#75bff7 0 33%,#fff 33% 66%,#75bff7 66%)}}.flag-aut{{background:linear-gradient(#d51f2f 0 33%,#fff 33% 66%,#d51f2f 66%)}}.flag-swe{{background:linear-gradient(90deg,transparent 0 28%,#f7d116 28% 42%,transparent 42%),linear-gradient(transparent 0 38%,#f7d116 38% 56%,transparent 56%),#0b5ca8}}.flag-jor{{background:linear-gradient(90deg,#d51f2f 0 33%,transparent 33%),linear-gradient(#000 0 33%,#fff 33% 66%,#198754 66%)}}
.sponsor-rail{{margin-top:8px;padding:9px}}.sponsor-heading{{display:flex;align-items:center;justify-content:space-between;gap:12px}}.sponsor-inventory-cta{{min-width:160px}}.sponsor-slots{{display:grid;grid-template-columns:repeat(5,1fr);gap:7px}}.sponsor-slots article{{height:44px;display:grid;place-items:center;border:1px dashed var(--line);background:rgba(216,166,75,.1);text-transform:uppercase;text-align:center;font-size:8px;font-weight:900;color:#d8e3e6}}.card-image-slot{{height:58px;margin:5px 0}}.photo-card p{{margin-bottom:4px;font-size:9px}}.photo-card ul{{margin:0 0 5px;padding-left:14px;font-size:7.8px}}.bottom-cta{{margin-top:auto}}.responsibility-panel{{margin-top:8px;padding:11px}}.responsibility-grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}}.responsibility-grid article{{display:flex;flex-direction:column;border:1px solid var(--blue);background:rgba(255,255,255,.035);padding:8px;min-height:108px}}.responsibility-grid h3{{color:var(--gold2);font-size:9px;text-transform:uppercase}}.responsibility-grid p{{margin:0;color:#d5e0e5;font-size:7.7px;line-height:1.25}}.read-more{{margin-top:auto;color:var(--gold2);font-size:7.5px;font-weight:900;text-transform:uppercase}}.site-footer{{padding-top:13px;margin-top:8px;border-top:1px solid rgba(216,166,75,.28)}}.footer-grid{{display:grid;grid-template-columns:repeat(6,1fr);gap:10px}}.footer-brand{{display:flex;align-items:center;gap:7px;min-width:0}}.footer-logo-placeholder{{width:44px;height:44px}}.footer-brand-name{{font-size:9px;letter-spacing:.06em;text-transform:uppercase;font-weight:900}}.footer-links h3{{margin:0 0 6px;font-size:7.5px;text-transform:uppercase}}.footer-links a,.footer-contact a,.footer-contact span{{display:block;margin-bottom:4px;color:#c5d1d7;font-size:7.6px}}.social-row{{display:flex;gap:5px;margin-top:7px}}.social-icon{{width:18px;height:18px;border-radius:3px}}.fine-print{{margin:10px 0 0;color:#7f9199;font-size:7px;text-align:center}}
@media (max-width:900px){{.page-shell{{padding-inline:12px}}.site-header{{top:29px;grid-template-columns:82px 1fr;grid-auto-rows:auto;padding-bottom:8px}}.brand-cell{{justify-content:flex-start}}.primary-nav{{grid-column:1/-1;overflow-x:auto;justify-content:flex-start;padding:0 4px 4px}}.primary-nav a{{flex:0 0 auto;padding-inline:8px}}.header-cta{{grid-column:1/-1;width:100%}}.hero-section{{margin-inline:-12px}}.path-grid{{grid-template-columns:repeat(3,1fr)}}.command-grid-primary,.command-grid-lower,.responsibility-grid,.footer-grid{{grid-template-columns:repeat(2,1fr)}}.sponsor-slots{{grid-template-columns:repeat(3,1fr)}}.inquiry-form{{grid-template-columns:repeat(2,1fr)}}.field-wide,.field-notes,.matchday-calendar,.secure-note{{grid-column:1/-1;grid-row:auto}}.map-layout{{grid-template-columns:1fr}}}}
@media (max-width:560px){{.approval-banner{{font-size:9px}}.site-header{{grid-template-columns:74px 1fr;top:26px}}.site-logo{{width:64px;height:46px}}.brand-name{{font-size:11px}}.hero-section{{min-height:320px}}.hero-section h1{{font-size:31px}}.eyebrow{{font-size:19px}}.hero-subtitle{{font-size:10px}}.inquiry-panel{{grid-template-columns:1fr}}.ai-image-slot{{min-height:92px}}.path-grid,.opening-team-grid,.sponsor-slots,.command-grid-primary,.command-grid-lower,.responsibility-grid,.footer-grid{{grid-template-columns:1fr}}.footer-brand{{justify-content:center;text-align:center}}}}
</style>
</head>
<body data-template="v1.0.10-clean-visual-copy" data-asset-boundary="header-logo-approved-only">
<div class="approval-banner">Production-readiness preview candidate — approved header logo embedded — remaining visual assets pending approval — not production approved</div>
<a class="skip-link" href="#main">Skip to command hub</a>
<div class="page-shell">
<header class="site-header" aria-label="Homepage header"><a class="logo-cell" href="#top" aria-label="DFW Matchday Concierge"><img class="site-logo" src="{logo_src}" alt="DFW Matchday Concierge" width="76" height="54" decoding="async" /></a><div class="brand-cell"><div class="brand-name"><span class="brand-dfw">DFW</span><br/>Matchday Concierge</div></div><nav class="primary-nav" aria-label="Primary"><a href="#inquiry">Inquiry</a><a href="#paths">Command Paths</a><a href="#routes">Routes</a><a href="#teams">Team Hubs</a><a href="#partners">Sponsors</a><a href="#support">Support</a><a href="#responsibility">Responsibility</a></nav><a class="button button-gold header-cta" href="#inquiry">Start Planning</a></header>
<main id="main"><section class="hero-section" id="top"><div class="hero-content"><p class="eyebrow">Dallas / Fort Worth</p><h1>Matchday Planning<br/>Command Hub Activated</h1><p class="hero-subtitle">One operating system for world-class matchday planning, movement, guest support, and local discovery.</p><div class="hero-actions"><a class="button button-gold" href="#inquiry">Build Matchday Plan <span aria-hidden="true">→</span></a><a class="button button-dark command-preview" href="#responsibility">Preview Command Hub <span aria-hidden="true">→</span></a></div><p class="hero-note">Operator-assisted planning. Confirmed scope. Matchday support.</p></div></section>
<section class="panel inquiry-panel" id="inquiry"><div class="image-slot ai-image-slot" aria-label="AI inquiry visual pending approval"></div><div><div class="split-heading"><div class="panel-heading"><h2>AI-Assisted Inquiry Intake</h2><p>Build the matchday profile before pricing, routing, or fulfillment is confirmed.</p></div><div class="status-badge">Activation Required</div></div><form class="inquiry-form"><div class="field"><label>Guest Type</label><select><option>VIP Guest</option><option>Team Family</option><option>Media / Corporate</option><option>Fan Hub</option></select></div><div class="field"><label>Arrival Date</label><input type="date" /></div><div class="field"><label>Airport / Area</label><input placeholder="DFW, DAL, hotel, suite" /></div><div class="field field-wide"><label>Planning Need</label><input placeholder="Transport, itinerary, luggage, food, hospitality" /></div><button class="button button-gold form-submit" type="button">Open Intake</button><div class="matchday-calendar"><b>Opening Dallas Window</b><span>Jun 14</span><span>Jun 17</span><span>Jun 22</span><span>Jun 25</span></div><p class="secure-note">No public booking is confirmed from this preview.</p></form></div></section>
<section class="panel paths-panel" id="paths"><h2>Command Paths</h2><div class="path-grid">{''.join([f'<article class="path-card"><div class="icon-placeholder"></div><h3>{t}</h3><p>{d}</p></article>' for t,d in [('VIP Guest Concierge','Private guest planning, timing, movement, and support.'),('Team Family Support','Family arrival, housing, daily flow, and local needs.'),('Media / Corporate','Credentials, executive arrivals, route timing, and hosting.'),('Fan Hubs','Group planning, fan movement, and local discovery.'),('Driver Onboarding','Driver profile, vehicle standards, and command view.'),('Concierge Onboarding','Errand, hospitality, luggage, and support tasks.'),('Fulfillment Hub','Food, retail, supplies, and local provider coordination.')]])}</div></section>
<div class="command-grid command-grid-primary"><section class="panel map-panel" id="routes"><div class="map-layout"><div class="map-visual"></div><div class="route-list"><h2>DFW Map & Routes</h2><a>DFW Airport ↔ Arlington Stadium District</a><a>Love Field ↔ Dallas Hotels</a><a>Fort Worth ↔ Arlington Matchday Core</a><a>Stockyards / Downtown Fort Worth</a><a>Fan zones, merchandise, food, and sponsor stops</a><a class="button button-outline route-cta" href="#inquiry">Route Plan Request</a></div></div></section><section class="panel team-mini-panel" id="teams"><h2>Team Family & Fan Hubs</h2><div class="opening-team-grid">{''.join([f'<article><span class="flag flag-{c}"></span><b>{n}</b></article>' for c,n in [('ned','Netherlands'),('jpn','Japan'),('eng','England'),('cro','Croatia'),('arg','Argentina'),('aut','Austria'),('swe','Sweden'),('jor','Jordan')]])}</div><a class="button button-gold team-hubs-cta" href="#inquiry">Preview Team Hub</a></section></div>
<section class="panel sponsor-rail" id="partners"><div class="sponsor-heading"><div><h2>Partner / Sponsor Rail</h2><p>Premium local discovery and placement inventory remains controlled until approval.</p></div><a class="button button-outline sponsor-inventory-cta" href="#responsibility">Inventory Pending</a></div><div class="sponsor-slots"><article>Hotel</article><article>Dining</article><article>Retail</article><article>Experiences</article><article>Local Services</article></div></section>
<div class="command-grid command-grid-lower" id="support"><section class="panel photo-card"><h2>Driver Command View</h2><div class="card-image-slot"></div><p>Operator-assisted movement planning, standards, vehicle fit, timing, and handoff notes.</p><ul><li>Arrival/departure timing</li><li>Airport and hotel routing</li><li>Guest profile and luggage notes</li></ul><a class="button button-dark bottom-cta" href="#inquiry">Driver Profile</a></section><section class="panel photo-card"><h2>Concierge Command View</h2><div class="card-image-slot"></div><p>Hospitality, errands, guest support, itinerary support, local discovery, and in-market assistance.</p><ul><li>Food, supplies, and retail</li><li>Guest support tasking</li><li>Daily plan coordination</li></ul><a class="button button-dark bottom-cta" href="#inquiry">Concierge Profile</a></section><section class="panel photo-card"><h2>Fulfillment Providers</h2><div class="card-image-slot"></div><p>Support provider lanes remain restricted until approved source assets and partner terms are confirmed.</p><ul><li>Provider activation</li><li>Service scope validation</li><li>Command hub visibility</li></ul><a class="button button-dark bottom-cta" href="#inquiry">Provider Intake</a></section></div>
<section class="panel responsibility-panel" id="responsibility"><h2>Governed Responsibility Cards</h2><div class="responsibility-grid"><article><h3>Scope Before Claim</h3><p>No public claim appears unless it maps to live, operator-assisted, development, or restricted capability.</p><span class="read-more">Read More</span></article><article><h3>Approval Boundary</h3><p>Only the header logo is approved. All non-header visuals remain pending approved assets.</p><span class="read-more">Read More</span></article><article><h3>Human Operator Layer</h3><p>Concierge support remains operator-assisted and subject to confirmation before fulfillment.</p><span class="read-more">Read More</span></article><article><h3>Launch Readiness</h3><p>Production deployment remains blocked until validation, mobile, QR, claim, and user approval pass.</p><span class="read-more">Read More</span></article></div></section></main>
<footer class="site-footer"><div class="footer-grid"><div class="footer-brand"><div class="footer-logo-placeholder"></div><div class="footer-brand-name">DFW<br/>Matchday Concierge</div></div><div class="footer-links"><h3>Plan</h3><a href="#inquiry">Inquiry</a><a href="#routes">Routes</a><a href="#teams">Team Hubs</a></div><div class="footer-links"><h3>Support</h3><a href="#support">Driver</a><a href="#support">Concierge</a><a href="#support">Fulfillment</a></div><div class="footer-links"><h3>Governance</h3><a href="#responsibility">Claims</a><a href="#responsibility">Assets</a><a href="#responsibility">Validation</a></div><address class="footer-contact"><h3>Contact</h3><a href="tel:+12148926827">214-892-6827</a><span>Dallas / Fort Worth</span></address><div><h3>Social</h3><div class="social-row"><span class="social-icon"></span><span class="social-icon"></span><span class="social-icon"></span><span class="social-icon"></span></div></div></div><p class="fine-print">Preview candidate. Header logo approved. Remaining visual assets pending approval. User approval not granted.</p></footer>
</div>
<script type="application/json" id="dfw-asset-approval-boundary">{{"approved":["Header logo"],"pending_approved_asset":["Footer logo","Hero image","AI inquiry image","VIP Guest Concierge hub icon","Team Family Support hub icon","Media / Corporate hub icon","Fan Hubs hub icon","Driver Onboarding hub icon","Concierge Onboarding hub icon","Fulfillment Hub icon","DFW map/routes image","Driver image","Concierge image","Fulfillment Providers image","Instagram icon","Facebook icon","X icon","LinkedIn icon","Any additional image/icon not explicitly approved"]}}</script>
</body>
</html>
'''

TARGET.write_text(html, encoding='utf-8')
RECORD.write_text(f'''# DFW v1.0.10 Exact Visual Copy Clean Template Rebuild Execution Record

Mission: `dfw_homepage_v1_0_10_exact_visual_copy_clean_template_rebuild_execution_v1_0_0`

Date: {now}

Status: REQUIRED-CORRECTION until Pages deployment, HTTP 200, desktop/tablet/mobile rendered validation, and user approval pass.

## Execution method

Repo-native GitHub Actions/local filesystem rebuild. The active preview URL is unchanged. The defective generated target file is preserved as governed diagnostic evidence before replacement.

## Preserved diagnostic file

`{DIAGNOSTIC.relative_to(ROOT)}`

## Rebuilt active target

`{TARGET.relative_to(ROOT)}`

## Results

- Visual design intent: preserve / exact-copy target.
- HTML/CSS architecture: rebuilt with clean semantic HTML and browser-safe CSS.
- Image system: rebuilt.
- Approved header logo: direct PNG data URI `img` sourced from the approved base64 file.
- Non-header visual slots: intentional Pending Approved Asset panels.
- Canary-image logic: removed from the rendered preview surface.
- Old header logo path reference: removed from rebuilt template.
- Misleading full-approved-assets wording: removed.
- JavaScript: no critical rendering JavaScript required.

## Validation standing

- Source-level rebuild: PASS.
- Desktop rendered proof: NOT PROVEN.
- Tablet rendered proof: NOT PROVEN.
- Mobile rendered proof: NOT PROVEN.
- HTTP 200 / non-404: NOT PROVEN.
- User approval: NOT GRANTED.

## 50+ page foundation readiness

NOT READY until rendered desktop/tablet/mobile validation and user approval pass.

## Production readiness standing

BLOCKED / REQUIRED-CORRECTION.
''', encoding='utf-8')
print('Rebuilt clean v1.0.10 template at', TARGET)
print('Preserved diagnostic at', DIAGNOSTIC)
print('Target URL:', URL)
